apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "broker-api.fullname" . }}
  labels:
  {{- include "broker-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "broker-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "broker-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: port-check
          image: solsson/websocat
          command:
            - sh
            - -c
            - |
              set -xe
              while true; do
                echo system_health | websocat {{ .Values.config.stateChainWsEndpoint }} --jsonrpc
                if [ $? -eq 0 ]; then
                  exit 0
                fi
                sleep 1
              done
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/chainflip-broker-api
          args:
            - --port={{ .Values.containerPort }}
            - --state_chain.signing_key_file={{ .Values.config.key.basePath }}/{{ .Values.config.key.signingKeyFileName }}
            - --state_chain.ws_endpoint={{ .Values.config.stateChainWsEndpoint }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: key
              mountPath: {{ .Values.config.key.basePath }}
      {{- with .Values.affinity }}
      affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: key
          secret:
            secretName: {{ .Values.config.key.existingSecret | default (include "broker-api.fullname" .) }}
            items:
              - key: {{ .Values.config.key.existingSecretKey | default "signing-key" }}
                path: {{ .Values.config.key.signingKeyFileName }}
