apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chainflip-prometheus-exporter.fullname" . }}-metrics"
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: "{{ include "chainflip-prometheus-exporter.fullname" . }}"
  ports:
    - port: {{ .Values.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  type: ClusterIP
