apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chainflip-prometheus-exporter.fullname" . }}-metrics"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
spec:
  selector:
    app: "{{ include "chainflip-prometheus-exporter.fullname" . }}"
  ports:
    - port: {{ .Values.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  type: ClusterIP
