{{- if not .Values.config.key.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lp-api.fullname" . }}
  labels:
    {{- include "lp-api.labels" . | nindent 4 }}
data:
  signing-key: {{ required "Please provide a value for .Values.config.key.signingKey" .Values.config.key.signingKey | b64enc | quote }}
{{- end }}