{{- if eq .Values.common.role "validator" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainflip-engine.fullname" . }}
  {{- with .Values.engine.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "chainflip-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.engine.service.type }}
  clusterIP: {{ .Values.engine.settings.node_p2p.ip_address | required "You must set an IP address for the node_p2p section e.g. 172.20.220.1" }}
  ports:
    - name: ip
      port: {{ .Values.engine.ports.ip }}
      targetPort: ip
      protocol: TCP
    {{- if .Values.engine.healthcheck.enabled }}
    - name: healthcheck
      port: {{ .Values.engine.healthcheck.port }}
      targetPort: healthcheck
      protocol: TCP
    {{- end }}
  selector:
    {{- include "chainflip-engine.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.engine.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainflip-engine.fullname" . }}-metrics
  {{- with .Values.engine.metrics.service.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
  labels:
  {{- include "chainflip-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.engine.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.engine.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
  {{- include "chainflip-engine.selectorLabels" . | nindent 4 }}
{{- end }}