{{- if eq .Values.common.role "validator" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chainflip-engine.fullname" . }}
  labels:
    {{- include "chainflip-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chainflip-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "chainflip-engine.fullname" . }}
      labels:
        {{- include "chainflip-engine.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: port-check
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              set -x
              while true; do
                nc -zv {{ include "chainflip-node.fullname" . }} {{ .Values.node.ports.rpc }}
                if [ $? -eq 0 ]; then
                  exit 0
                fi
                sleep 1
              done
      containers:
        - name: chainflip-engine
          image: "{{ include "chainflip-engine.image" . }}"
          command:
            - /usr/local/bin/chainflip-engine
          args:
            - --config-root={{ .Values.common.basePath }}
          {{- with .Values.engine.extraArgs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if  .Values.engine.healthcheck.enabled }}
            - containerPort: {{ .Values.engine.healthcheck.port }}
              name: healthcheck
            {{- end }}
            - containerPort: {{ .Values.engine.ports.ip }}
              name: ip
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: healthcheck
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: healthcheck
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          {{- with .Values.engine.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.common.basePath }}
            - name: keys
              mountPath: {{ .Values.common.keys.keysPath }}
              readOnly: true
            - name: settings
              mountPath: {{ .Values.common.basePath }}/config
              readOnly: true
      volumes:
        - name: settings
          configMap:
            name: {{ .Values.engine.settings.existingConfigMap | default (include "chainflip-engine.fullname" .) }}
        - name: keys
          secret:
            secretName: {{ include "node.fullname" . }}
            items:
              - key: node-key
                path: node_key_file
              - key: signing-key
                path: signing_key_file
              - key: ethereum-key
                path: ethereum_key_file
        {{- if .Values.engine.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.engine.persistence.existingClaim }}
        {{- end }}
  {{- if eq .Values.engine.persistence.existingClaim "" }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "chainflip-engine.selectorLabels" . | nindent 10 }}
      spec:
        {{- with .Values.engine.persistence.accessModes }}
        accessModes:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.engine.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: "{{ .Values.engine.persistence.size }}"
  {{- end }}
{{- end }}