apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chainflip-node.fullname" . }}
  labels:
  {{- include "chainflip-node.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chainflip-node.fullname" . }}
  selector:
    matchLabels:
  {{- include "chainflip-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "chainflip-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- if or .Values.network.chain.chainspecUrl (eq .Values.common.role "validator") .Values.common.keys.generateKeysOnStart }}
      initContainers:
        {{- if .Values.network.chain.chainspecUrl }}
        - name: download-chainspec
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              curl -L -o {{ include "chainflip-node.chain" . }} {{ .Values.network.chain.chainspecUrl }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.common.basePath }}
        {{- end }}
        {{- if eq .Values.common.role "validator" }}
        - name: inject-keys
          image: {{ include "chainflip-node.image" . }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data
              mountPath: {{ .Values.common.basePath }}
            - name: keys
              mountPath: {{ .Values.common.keys.keysPath }}
          command:
            - /bin/sh
            - -c
            - |
              chainflip-node key insert \
                --key-type 'aura' \
                --scheme sr25519 \
                --chain {{ include "chainflip-node.chain" . }} \
                --suri "0x$(cat {{ .Values.common.keys.keysPath }}/{{ .Values.common.keys.signingKeyFileName }})" \
                --base-path {{ .Values.common.basePath }}
              chainflip-node key insert \
                --key-type 'gran' \
                --scheme ed25519 \
                --chain {{ include "chainflip-node.chain" . }} \
                --suri "0x$(cat {{ .Values.common.keys.keysPath }}/{{ .Values.common.keys.signingKeyFileName }})" \
                --base-path {{ .Values.common.basePath }}
          {{- end }}
          {{- end }}
      containers:
        - name: chainflip-node
          image: "{{ include "chainflip-node.image" . }}"
          imagePullPolicy: {{ .Values.node.image.pullPolicy }}
          command:
            - /usr/local/bin/chainflip-node
          args:
            - --base-path={{ .Values.common.basePath }}
            - --chain={{ include "chainflip-node.chain" . }}
            {{- range .Values.network.bootnodes }}
            - --bootnodes={{ . }}
            {{- end }}
            {{- if eq .Values.common.role "validator" }}
            - --node-key-file={{ .Values.common.keys.keysPath }}/{{ .Values.common.keys.nodeKeyFileName }}
            - --validator
            - --sync=warp
            {{- end }}
            {{- if eq .Values.common.role "archive" }}
            - --blocks-pruning=archive
            - --state-pruning=archive
            {{- end }}
            - --port={{ .Values.node.ports.p2p  }}
            - --ws-port={{ .Values.node.ports.ws }}
            - --rpc-port={{ .Values.node.ports.rpc }}
            {{- if .Values.node.metrics.enabled }}
            - --prometheus-port={{ .Values.node.metrics.port }}
            {{- if .Values.node.metrics.expose }}
            - --prometheus-external
            {{- end }}
            {{- end }}
            - --rpc-cors=all
            - --rpc-methods=unsafe
            - --unsafe-rpc-external
            - --unsafe-ws-external
            {{- with .Values.node.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: ws
              containerPort: {{ .Values.node.ports.ws }}
              protocol: TCP
            - name: rpc
              containerPort: {{ .Values.node.ports.rpc }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.node.ports.p2p }}
              protocol: TCP
            {{- if .Values.node.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.node.metrics.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.node.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.common.basePath }}
            - name: keys
              mountPath: {{ .Values.common.keys.keysPath }}
      volumes:
        {{- if eq .Values.common.role "validator" }}
        - name: keys
          secret:
            secretName: {{ .Values.common.keys.existingSecret | default (include "node.fullname" .) }}
            items:
              - key: signing-key
                path: {{ .Values.common.keys.signingKeyFileName }}
              - key: node-key
                path: {{ .Values.common.keys.nodeKeyFileName }}
              - key: ethereum-key
                path: {{ .Values.common.keys.ethereumKeyFileName }}
        {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "chainflip-node.labels" . | nindent 10 }}
      spec:
        {{- with .Values.node.persistence.accessModes }}
        accessModes:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.node.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: "{{ .Values.node.persistence.size }}"