apiVersion: v2
name: chainflip-prometheus-exporter
version: 2.0.13
appVersion: 2.3.8
description: Scrape data from all supported chains
maintainers:
  - name: Chainflip Labs
    email: dev@chainflip.io
    url: https://chainflip.io
type: application