apiVersion: v2
name: chainflip-prometheus-exporter
version: 1.2.1
appVersion: 1.2.1
description: Scrape data from all supported chains
maintainers:
  - name: Chainflip Labs
    email: dev@chainflip.io
    url: https://chainflip.io
type: application