name: CI PR
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Lint charts
        run: |
          helm lint ./charts/*
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Install helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Test charts
        run: |
          helm unittest ./charts/* 

  check_version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          chart: [broker-api, node]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get all Charts that have changed
      id: changed-files
      uses: tj-actions/changed-files@v38
      with:
        files_yaml: |
          chart:
            - charts/${{ matrix.chart }}/**

    - name: Check Chart.yaml version
      if: steps.changed-files.outputs.chart_any_changed == 'true'
      run: |
        bash ci/scripts/check_chart_yaml_version.sh ${{ matrix.chart }}