name: CI PR
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Lint charts
        run: |
          helm lint ./charts/*
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Install helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Test charts
        run: |
          helm unittest ./charts/*

  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # fetch the last two commits

    - name: Check Chart.yaml version
      run: |

To check if the chart.yaml version has been updated relative to the main branch, you can modify the GitHub Action to compare the changes against the main branch instead of the previous commit. Here's how to do it:

Create a .github/workflows/check_chart_version.yml in your repository.

Populate the file with the following content:

yaml
Copy code
name: Check chart.yaml version update

on:
  pull_request:
    paths:
      - 'path_to_chart_folder/chart.yaml'

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Chart.yaml version
      run: |
        git fetch origin main:main
        VERSION_PR=$(yq .version charts/node/Chart.yaml)
        git checkout main
        VERSION_MAIN=$(yq .version charts/node/Chart.yaml)
        if [ "$VERSION_PR" == "$VERSION_MAIN" ]; then
          echo "chart.yaml version has not been updated!"
          exit 1
        else
          echo "chart.yaml version has been updated."
        fi