# -- override the naming of the node chart
fullnameOverride: ""

# -- override the default value of the name
nameOverride: ""

# -- select an existing secret where your repository credentials are stored
imagePullSecrets: []

# -- shared settings across the chainflip-engine and chainflip-node
common:
  # -- desired role for your node; `validator` or `archive`
  role: "validator" # validator, archive

  # -- root path for the chainflip configuration
  basePath: /etc/chainflip

  # -- default path for validator keys
  keys:
    # -- use the chainflip-cli to inject all keys on start
    generateKeysOnStart: false

    # -- base path for all keys
    keysPath: /etc/chainflip/keys

    # -- node key file name
    nodeKeyFileName: node_key_file

    # -- node key; recommended to leave empty and provide through a secret
    nodeKey: ""

    # -- signing key file name
    signingKeyFileName: signing_key_file

    # -- signing key; recommended to leave empty and provide through a secret
    signingKey: ""

    # -- ethereum key file name
    ethereumKeyFileName: ethereum_key_file

    # -- ethereum key; recommended to leave empty and provide through a secret
    ethereumKey: ""

    # -- exiting secret with keys
    existingSecret: ""

network:
  # -- chain settings
  chain:
    # -- chain name; `perseverance`
    name: "perseverance"

    # -- download the chainspec from a URL
    chainspecUrl: "https://s3.eu-central-1.amazonaws.com/repo.chainflip.io/chainspecs/perseverance.chainspec.json"

  # -- network bootnodes
  bootnodes:
    - /ip4/167.99.129.29/tcp/30333/p2p/12D3KooWPFZo5JzqiWASDSrAtbyKgW2kw4Rb5FruE29PAhJ1u4xL


# -- chainflip-node configuration
node:
  # -- override the default value of the node pod
  fullnameOverride: ""

  # -- chainflip-node image settings
  image:
    # -- chainflip-node image repository
    repository: chainfliplabs/chainflip-node

    # -- chainflip-node image tag; default to `network.chain.name`
    tag: ""

    # -- chainflip-node image pull policy
    pullPolicy: Always

  # -- chainflip-node extra arguments
  extraArgs:
    - --name="Chainflip Node"

  # -- set extra environment variables
  extraEnv: []

  # -- set extra environment variables from a secret
  extraEnvFrom: []

  # -- ports exposed by the chainflip-node
  ports:
    # -- chainflip-node ws port
    ws: "9944"
    # -- chainflip-node rpc port
    rpc: "9933"
    # -- chainflip-node p2p port
    p2p: "30333"

  metrics:
    # -- enable prometheus metrics
    enabled: true

    # -- prometheus metrics port
    port: 9615

    # -- expose prometheus metrics
    expose: true

  # -- chainflip-node resources
  resources: {}

  # -- chaindata volume settings
  persistence:
    # -- enable chaindata persistence
    enabled: true

    # -- reference an existing PVC
    existingClaim: ""

    # -- chaindata volume size
    size: 100Gi

    # -- chaindata volume storage class
    storageClass: ""

    # -- chaindata volume access mode
    accessModes:
      - ReadWriteOnce

  # -- chainflip-node service configuration
  service:
    # -- chainflip-node service type
    type: ClusterIP

    # -- chainflip-node service port
    port: 80

    # -- chainflip-node service annotations
    annotations: {}

  # -- set node selector
  nodeSelector: {}

  # -- set pod affinity
  affinity: {}

  # -- set pod tolerations
  tolerations: []

# -- chainflip-engine configuration
engine:
  # -- override the default value of the engine pod
  fullnameOverride: ""

  # -- chainflip-engine image settings
  image:
    # -- chainflip-engine image repository
    repository: chainfliplabs/chainflip-engine

    # -- chainflip-engine image tag
    tag: ""

    # -- chainflip-engine image pull policy
    pullPolicy: Always

  # -- chainflip-engine extra arguments
  extraArgs: {}

  # -- set extra environment variables
  extraEnv: []

  # -- set extra environment variables from a secret
  extraEnvFrom: []

  # -- chainflip-engine resources
  resources: {}

  # -- chainflip-engine ports
  ports:
    # -- chainflip-engine p2p port
    ip: "8078"

  # -- chainflip-engine healthcheck settings
  healthcheck:
    # -- enable chainflip-engine healthcheck
    enabled: true

    # -- chainflip-engine healthcheck hostname
    hostname: "0.0.0.0"

    # -- chainflip-engine healthcheck port
    port: "5555"

  # -- chainflip-engine persistence settings
  persistence:
    # -- enable chainflip-engine persistence
    enabled: true

    # -- reference an existing PVC
    existingClaim: ""

    # -- chainflip-engine volume size
    size: 5Gi

    # -- chainflip-engine volume storage class
    storageClass: ""

    # -- chainflip-engine volume access mode
    accessModes:
    - ReadWriteOnce

  # -- chainflip-engine Settings.toml configuration
  settings:
    # -- existing configMap with Settings.toml
    existingConfigMap: ""

    # -- node_p2p settings
    node_p2p:

      # -- local ip address; this will set the ClusterIP of the service
      ip_address: ""

      # -- allow local ip addresses
      allow_local_ip: true

    # -- ethereum settings
    eth:
      # -- ethereum node http endpoint
      ws_node_endpoint: ""

      # -- ethereum node ws endpoint
      http_node_endpoint: ""

    # -- polkadot settings
    dot:
      # -- polkadot node ws endpoint
      ws_node_endpoint: ""

      # -- polkadot node http endpoint
      http_node_endpoint: ""

    # -- bitcoin settings
    btc:
      # -- bitcoin node http endpoint
      http_node_endpoint: ""

      # -- bitcoin rpc user
      rpc_user: "flip"

      # -- bitcoin rpc password
      rpc_password: "flip"

  # -- chainflip-engine service configuration
  service:
    # -- chainflip-engine service type
    type: ClusterIP

    # -- chainflip-engine service port
    port: 80

    # -- chainflip-engine service annotations
    annotations: {}

  # -- define extra init containers on the engine
  extraInitContainers: []

  # -- set node selector
  nodeSelector: {}

  # -- set pod affinity
  affinity: {}

  # -- set pod tolerations
  tolerations: []

# -- chainflip-cli configuration
cli:
  # -- enable chainflip-cli
  enabled: true

  # -- chainflip-cli image settings
  image:
    # -- chainflip-cli image repository
    repository: chainfliplabs/chainflip-cli

    # -- chainflip-cli image tag
    tag: ""

    # -- chainflip-cli image pull policy
    pullPolicy: Always

# -- hook configuration
hook:
  # -- add extra annotations to the create-keys hook
  extraAnnotations: {}

# -- create extra kubernetes manifests
extraManifests: []